# Generated by Django 4.1.5 on 2023-01-29 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("guineapig", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="security_token",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="birthday",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="insurance_company",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="num_of_kids",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="plan_type",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="state",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="zipcode",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
